//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.GuiClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.GuiClient.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADMINFORM_ADDRESS {
            get {
                return ResourceManager.GetString("ADMINFORM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ADMINFORM_ADMIN {
            get {
                return ResourceManager.GetString("ADMINFORM_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cid.
        /// </summary>
        public static string ADMINFORM_CID {
            get {
                return ResourceManager.GetString("ADMINFORM_CID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ADMINFORM_CLOSE {
            get {
                return ResourceManager.GetString("ADMINFORM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections opened with selected session.
        /// </summary>
        public static string ADMINFORM_CONNECTIONS {
            get {
                return ResourceManager.GetString("ADMINFORM_CONNECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ADMINFORM_HOST {
            get {
                return ResourceManager.GetString("ADMINFORM_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill connection.
        /// </summary>
        public static string ADMINFORM_KILL_CONNECTION {
            get {
                return ResourceManager.GetString("ADMINFORM_KILL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t kill your active session.
        /// </summary>
        public static string ADMINFORM_KILL_OWN_SESSION {
            get {
                return ResourceManager.GetString("ADMINFORM_KILL_OWN_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill session.
        /// </summary>
        public static string ADMINFORM_KILL_SESSION {
            get {
                return ResourceManager.GetString("ADMINFORM_KILL_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastAccess.
        /// </summary>
        public static string ADMINFORM_LAST_ACCESS {
            get {
                return ResourceManager.GetString("ADMINFORM_LAST_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string ADMINFORM_LOGON {
            get {
                return ResourceManager.GetString("ADMINFORM_LOGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ADMINFORM_PORT {
            get {
                return ResourceManager.GetString("ADMINFORM_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadCount.
        /// </summary>
        public static string ADMINFORM_READ_COUNT {
            get {
                return ResourceManager.GetString("ADMINFORM_READ_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ADMINFORM_REFRESH {
            get {
                return ResourceManager.GetString("ADMINFORM_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string ADMINFORM_SESSIONS {
            get {
                return ResourceManager.GetString("ADMINFORM_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sid.
        /// </summary>
        public static string ADMINFORM_SID {
            get {
                return ResourceManager.GetString("ADMINFORM_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel (Client) - Administration.
        /// </summary>
        public static string ADMINFORM_TITLE {
            get {
                return ResourceManager.GetString("ADMINFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ADMINFORM_USER {
            get {
                return ResourceManager.GetString("ADMINFORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteCount.
        /// </summary>
        public static string ADMINFORM_WRITE_COUNT {
            get {
                return ResourceManager.GetString("ADMINFORM_WRITE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote admin server....
        /// </summary>
        public static string MAINFORM_ADMIN_SERVER {
            get {
                return ResourceManager.GetString("MAINFORM_ADMIN_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client started.
        /// </summary>
        public static string MAINFORM_CLIENT_STARTED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client starting....
        /// </summary>
        public static string MAINFORM_CLIENT_STARTING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client stopped.
        /// </summary>
        public static string MAINFORM_CLIENT_STOPPED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client stopping....
        /// </summary>
        public static string MAINFORM_CLIENT_STOPPING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel Client v{0}.
        /// </summary>
        public static string MAINFORM_CLIENT_TITLE {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure client....
        /// </summary>
        public static string MAINFORM_CONFIGURE_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_CONFIGURE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MAINFORM_EXIT {
            get {
                return ResourceManager.GetString("MAINFORM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until processing is complete....
        /// </summary>
        public static string MAINFORM_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("MAINFORM_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start client.
        /// </summary>
        public static string MAINFORM_START_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_START_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop client.
        /// </summary>
        public static string MAINFORM_STOP_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_STOP_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View logs.
        /// </summary>
        public static string MAINFORM_VIEW_LOGS {
            get {
                return ResourceManager.GetString("MAINFORM_VIEW_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string PROXYFORM_APPLY {
            get {
                return ResourceManager.GetString("PROXYFORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication required:.
        /// </summary>
        public static string PROXYFORM_AUTH_REQUESTED {
            get {
                return ResourceManager.GetString("PROXYFORM_AUTH_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PROXYFORM_CANCEL {
            get {
                return ResourceManager.GetString("PROXYFORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string PROXYFORM_DOMAIN {
            get {
                return ResourceManager.GetString("PROXYFORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PROXYFORM_PASSWORD {
            get {
                return ResourceManager.GetString("PROXYFORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel (Client) - Authentication.
        /// </summary>
        public static string PROXYFORM_TITLE {
            get {
                return ResourceManager.GetString("PROXYFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string PROXYFORM_USER {
            get {
                return ResourceManager.GetString("PROXYFORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string SETUPFORM_ADD_NEW {
            get {
                return ResourceManager.GetString("SETUPFORM_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SETUPFORM_ADDRESS {
            get {
                return ResourceManager.GetString("SETUPFORM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append to file.
        /// </summary>
        public static string SETUPFORM_APPEND_FILE {
            get {
                return ResourceManager.GetString("SETUPFORM_APPEND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string SETUPFORM_APPLY {
            get {
                return ResourceManager.GetString("SETUPFORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string SETUPFORM_AUTHENTIFICATION {
            get {
                return ResourceManager.GetString("SETUPFORM_AUTHENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string SETUPFORM_AUTO {
            get {
                return ResourceManager.GetString("SETUPFORM_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SETUPFORM_CANCEL {
            get {
                return ResourceManager.GetString("SETUPFORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string SETUPFORM_CONFIGURATION {
            get {
                return ResourceManager.GetString("SETUPFORM_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect through HTTP proxy.
        /// </summary>
        public static string SETUPFORM_CONNECT_THROUGH_PROXY {
            get {
                return ResourceManager.GetString("SETUPFORM_CONNECT_THROUGH_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console (unused by GUI client).
        /// </summary>
        public static string SETUPFORM_CONSOLE {
            get {
                return ResourceManager.GetString("SETUPFORM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        public static string SETUPFORM_CURRENT_POSITION {
            get {
                return ResourceManager.GetString("SETUPFORM_CURRENT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string SETUPFORM_DATE_FORMAT {
            get {
                return ResourceManager.GetString("SETUPFORM_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SETUPFORM_DELETE {
            get {
                return ResourceManager.GetString("SETUPFORM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string SETUPFORM_DOMAIN {
            get {
                return ResourceManager.GetString("SETUPFORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SETUPFORM_ENABLED {
            get {
                return ResourceManager.GetString("SETUPFORM_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 100-Continue behavior (restart needed).
        /// </summary>
        public static string SETUPFORM_EXPECT100 {
            get {
                return ResourceManager.GetString("SETUPFORM_EXPECT100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SETUPFORM_FILE {
            get {
                return ResourceManager.GetString("SETUPFORM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfiles|*.log|All files|*.*.
        /// </summary>
        public static string SETUPFORM_FILE_FILTER {
            get {
                return ResourceManager.GetString("SETUPFORM_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string SETUPFORM_FILTER {
            get {
                return ResourceManager.GetString("SETUPFORM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string SETUPFORM_FORMAT {
            get {
                return ResourceManager.GetString("SETUPFORM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        public static string SETUPFORM_FORWARDS {
            get {
                return ResourceManager.GetString("SETUPFORM_FORWARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP binary stream.
        /// </summary>
        public static string SETUPFORM_HTTP_BINARY_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_BINARY_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy.
        /// </summary>
        public static string SETUPFORM_HTTP_PROXY {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP SOAP stream.
        /// </summary>
        public static string SETUPFORM_HTTP_SOAP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_SOAP_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS binary stream.
        /// </summary>
        public static string SETUPFORM_HTTPS_BINARY_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTPS_BINARY_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS SOAP stream.
        /// </summary>
        public static string SETUPFORM_HTTPS_SOAP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTPS_SOAP_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string SETUPFORM_INVALID_INPUT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number must be set between {0} and {1}.
        /// </summary>
        public static string SETUPFORM_INVALID_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local binary stream.
        /// </summary>
        public static string SETUPFORM_IPC_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_IPC_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item count.
        /// </summary>
        public static string SETUPFORM_ITEM_COUNT {
            get {
                return ResourceManager.GetString("SETUPFORM_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        public static string SETUPFORM_ITEM_COUNT_OF {
            get {
                return ResourceManager.GetString("SETUPFORM_ITEM_COUNT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port.
        /// </summary>
        public static string SETUPFORM_LOCAL_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_LOCAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string SETUPFORM_MOVE_DOWN {
            get {
                return ResourceManager.GetString("SETUPFORM_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        public static string SETUPFORM_MOVE_FIRST {
            get {
                return ResourceManager.GetString("SETUPFORM_MOVE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to bottom.
        /// </summary>
        public static string SETUPFORM_MOVE_LAST {
            get {
                return ResourceManager.GetString("SETUPFORM_MOVE_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string SETUPFORM_MOVE_UP {
            get {
                return ResourceManager.GetString("SETUPFORM_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SETUPFORM_NAME {
            get {
                return ResourceManager.GetString("SETUPFORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SETUPFORM_PASSWORD {
            get {
                return ResourceManager.GetString("SETUPFORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SETUPFORM_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string SETUPFORM_PROTOCOL {
            get {
                return ResourceManager.GetString("SETUPFORM_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote port.
        /// </summary>
        public static string SETUPFORM_REMOTE_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_REMOTE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string SETUPFORM_SHARED {
            get {
                return ResourceManager.GetString("SETUPFORM_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks.
        /// </summary>
        public static string SETUPFORM_SOCKS {
            get {
                return ResourceManager.GetString("SETUPFORM_SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Socks server.
        /// </summary>
        public static string SETUPFORM_SOCKS_SERVER_ENABLED {
            get {
                return ResourceManager.GetString("SETUPFORM_SOCKS_SERVER_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Socks server.
        /// </summary>
        public static string SETUPFORM_SOCKS_SERVER_SHARED {
            get {
                return ResourceManager.GetString("SETUPFORM_SOCKS_SERVER_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP binary stream.
        /// </summary>
        public static string SETUPFORM_TCP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_TCP_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel (Client) - Configuration.
        /// </summary>
        public static string SETUPFORM_TITLE {
            get {
                return ResourceManager.GetString("SETUPFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        public static string SETUPFORM_TUNNEL {
            get {
                return ResourceManager.GetString("SETUPFORM_TUNNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SETUPFORM_USER {
            get {
                return ResourceManager.GetString("SETUPFORM_USER", resourceCulture);
            }
        }
    }
}
