//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.GuiClient.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.GuiClient.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client started.
        /// </summary>
        internal static string MAINFORM_CLIENT_STARTED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client starting....
        /// </summary>
        internal static string MAINFORM_CLIENT_STARTING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client stopped.
        /// </summary>
        internal static string MAINFORM_CLIENT_STOPPED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client stopping....
        /// </summary>
        internal static string MAINFORM_CLIENT_STOPPING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BoutDuTunnel Client v{0}.
        /// </summary>
        internal static string MAINFORM_CLIENT_TITLE {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure client....
        /// </summary>
        internal static string MAINFORM_CONFIGURE_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_CONFIGURE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string MAINFORM_EXIT {
            get {
                return ResourceManager.GetString("MAINFORM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait until processing is complete....
        /// </summary>
        internal static string MAINFORM_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("MAINFORM_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start client.
        /// </summary>
        internal static string MAINFORM_START_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_START_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop client.
        /// </summary>
        internal static string MAINFORM_STOP_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_STOP_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View logs.
        /// </summary>
        internal static string MAINFORM_VIEW_LOGS {
            get {
                return ResourceManager.GetString("MAINFORM_VIEW_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string PROXYFORM_APPLY {
            get {
                return ResourceManager.GetString("PROXYFORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy authentication required:.
        /// </summary>
        internal static string PROXYFORM_AUTH_REQUESTED {
            get {
                return ResourceManager.GetString("PROXYFORM_AUTH_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string PROXYFORM_CANCEL {
            get {
                return ResourceManager.GetString("PROXYFORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        internal static string PROXYFORM_DOMAIN {
            get {
                return ResourceManager.GetString("PROXYFORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string PROXYFORM_PASSWORD {
            get {
                return ResourceManager.GetString("PROXYFORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BoutDuTunnel (Client) - Authentication.
        /// </summary>
        internal static string PROXYFORM_TITLE {
            get {
                return ResourceManager.GetString("PROXYFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string PROXYFORM_USER {
            get {
                return ResourceManager.GetString("PROXYFORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new.
        /// </summary>
        internal static string SETUP_FORM_ADD_NEW {
            get {
                return ResourceManager.GetString("SETUP_FORM_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        internal static string SETUP_FORM_ADDRESS {
            get {
                return ResourceManager.GetString("SETUP_FORM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Append to file.
        /// </summary>
        internal static string SETUP_FORM_APPEND_FILE {
            get {
                return ResourceManager.GetString("SETUP_FORM_APPEND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string SETUP_FORM_APPLY {
            get {
                return ResourceManager.GetString("SETUP_FORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication.
        /// </summary>
        internal static string SETUP_FORM_AUTHENTIFICATION {
            get {
                return ResourceManager.GetString("SETUP_FORM_AUTHENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto.
        /// </summary>
        internal static string SETUP_FORM_AUTO {
            get {
                return ResourceManager.GetString("SETUP_FORM_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string SETUP_FORM_CANCEL {
            get {
                return ResourceManager.GetString("SETUP_FORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string SETUP_FORM_CONFIGURATION {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect through HTTP proxy.
        /// </summary>
        internal static string SETUP_FORM_CONNECT_THROUGH_PROXY {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONNECT_THROUGH_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console (unused by GUI client).
        /// </summary>
        internal static string SETUP_FORM_CONSOLE {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current position.
        /// </summary>
        internal static string SETUP_FORM_CURRENT_POSITION {
            get {
                return ResourceManager.GetString("SETUP_FORM_CURRENT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date format.
        /// </summary>
        internal static string SETUP_FORM_DATE_FORMAT {
            get {
                return ResourceManager.GetString("SETUP_FORM_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string SETUP_FORM_DELETE {
            get {
                return ResourceManager.GetString("SETUP_FORM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        internal static string SETUP_FORM_DOMAIN {
            get {
                return ResourceManager.GetString("SETUP_FORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        internal static string SETUP_FORM_ENABLED {
            get {
                return ResourceManager.GetString("SETUP_FORM_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string SETUP_FORM_FILE {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logfiles|*.log|All files|*.*.
        /// </summary>
        internal static string SETUP_FORM_FILE_FILTER {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string SETUP_FORM_FILTER {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string SETUP_FORM_FORMAT {
            get {
                return ResourceManager.GetString("SETUP_FORM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forwards.
        /// </summary>
        internal static string SETUP_FORM_FORWARDS {
            get {
                return ResourceManager.GetString("SETUP_FORM_FORWARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP Proxy.
        /// </summary>
        internal static string SETUP_FORM_HTTP_PROXY {
            get {
                return ResourceManager.GetString("SETUP_FORM_HTTP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Item count.
        /// </summary>
        internal static string SETUP_FORM_ITEM_COUNT {
            get {
                return ResourceManager.GetString("SETUP_FORM_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of {0}.
        /// </summary>
        internal static string SETUP_FORM_ITEM_COUNT_OF {
            get {
                return ResourceManager.GetString("SETUP_FORM_ITEM_COUNT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local port.
        /// </summary>
        internal static string SETUP_FORM_LOCAL_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_LOCAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move down.
        /// </summary>
        internal static string SETUP_FORM_MOVE_DOWN {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to top.
        /// </summary>
        internal static string SETUP_FORM_MOVE_FIRST {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to bottom.
        /// </summary>
        internal static string SETUP_FORM_MOVE_LAST {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move up.
        /// </summary>
        internal static string SETUP_FORM_MOVE_UP {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string SETUP_FORM_NAME {
            get {
                return ResourceManager.GetString("SETUP_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string SETUP_FORM_PASSWORD {
            get {
                return ResourceManager.GetString("SETUP_FORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string SETUP_FORM_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Protocol.
        /// </summary>
        internal static string SETUP_FORM_PROTOCOL {
            get {
                return ResourceManager.GetString("SETUP_FORM_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote port.
        /// </summary>
        internal static string SETUP_FORM_REMOTE_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_REMOTE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shared.
        /// </summary>
        internal static string SETUP_FORM_SHARED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks.
        /// </summary>
        internal static string SETUP_FORM_SOCKS {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Socks server.
        /// </summary>
        internal static string SETUP_FORM_SOCKS_SERVER_ENABLED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS_SERVER_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share Socks server.
        /// </summary>
        internal static string SETUP_FORM_SOCKS_SERVER_SHARED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS_SERVER_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BoutDuTunnel (Client) - Configuration.
        /// </summary>
        internal static string SETUP_FORM_TITLE {
            get {
                return ResourceManager.GetString("SETUP_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunnel.
        /// </summary>
        internal static string SETUP_FORM_TUNNEL {
            get {
                return ResourceManager.GetString("SETUP_FORM_TUNNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string SETUP_FORM_USER {
            get {
                return ResourceManager.GetString("SETUP_FORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP binary stream.
        /// </summary>
        internal static string SETUPFORM_HTTP_BINARY_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_BINARY_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP SOAP stream.
        /// </summary>
        internal static string SETUPFORM_HTTP_SOAP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_SOAP_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input.
        /// </summary>
        internal static string SETUPFORM_INVALID_INPUT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number must be set between {0} and {1}.
        /// </summary>
        internal static string SETUPFORM_INVALID_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local binary stream.
        /// </summary>
        internal static string SETUPFORM_IPC_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_IPC_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TCP binary stream.
        /// </summary>
        internal static string SETUPFORM_TCP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_TCP_REMOTING", resourceCulture);
            }
        }
    }
}
