//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.GuiClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.GuiClient.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client started.
        /// </summary>
        internal static string MAINFORM_CLIENT_STARTED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client starting....
        /// </summary>
        internal static string MAINFORM_CLIENT_STARTING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client stopped.
        /// </summary>
        internal static string MAINFORM_CLIENT_STOPPED {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client stopping....
        /// </summary>
        internal static string MAINFORM_CLIENT_STOPPING {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel Client v{0}.
        /// </summary>
        internal static string MAINFORM_CLIENT_TITLE {
            get {
                return ResourceManager.GetString("MAINFORM_CLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure client....
        /// </summary>
        internal static string MAINFORM_CONFIGURE_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_CONFIGURE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MAINFORM_EXIT {
            get {
                return ResourceManager.GetString("MAINFORM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until processing is complete....
        /// </summary>
        internal static string MAINFORM_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("MAINFORM_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start client.
        /// </summary>
        internal static string MAINFORM_START_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_START_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop client.
        /// </summary>
        internal static string MAINFORM_STOP_CLIENT {
            get {
                return ResourceManager.GetString("MAINFORM_STOP_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View logs.
        /// </summary>
        internal static string MAINFORM_VIEW_LOGS {
            get {
                return ResourceManager.GetString("MAINFORM_VIEW_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string PROXYFORM_APPLY {
            get {
                return ResourceManager.GetString("PROXYFORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication required:.
        /// </summary>
        internal static string PROXYFORM_AUTH_REQUESTED {
            get {
                return ResourceManager.GetString("PROXYFORM_AUTH_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PROXYFORM_CANCEL {
            get {
                return ResourceManager.GetString("PROXYFORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string PROXYFORM_DOMAIN {
            get {
                return ResourceManager.GetString("PROXYFORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PROXYFORM_PASSWORD {
            get {
                return ResourceManager.GetString("PROXYFORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel (Client) - Authentication.
        /// </summary>
        internal static string PROXYFORM_TITLE {
            get {
                return ResourceManager.GetString("PROXYFORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string PROXYFORM_USER {
            get {
                return ResourceManager.GetString("PROXYFORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string SETUP_FORM_ADD_NEW {
            get {
                return ResourceManager.GetString("SETUP_FORM_ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SETUP_FORM_ADDRESS {
            get {
                return ResourceManager.GetString("SETUP_FORM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append to file.
        /// </summary>
        internal static string SETUP_FORM_APPEND_FILE {
            get {
                return ResourceManager.GetString("SETUP_FORM_APPEND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SETUP_FORM_APPLY {
            get {
                return ResourceManager.GetString("SETUP_FORM_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string SETUP_FORM_AUTHENTIFICATION {
            get {
                return ResourceManager.GetString("SETUP_FORM_AUTHENTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string SETUP_FORM_AUTO {
            get {
                return ResourceManager.GetString("SETUP_FORM_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SETUP_FORM_CANCEL {
            get {
                return ResourceManager.GetString("SETUP_FORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string SETUP_FORM_CONFIGURATION {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect through HTTP proxy.
        /// </summary>
        internal static string SETUP_FORM_CONNECT_THROUGH_PROXY {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONNECT_THROUGH_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console (unused by GUI client).
        /// </summary>
        internal static string SETUP_FORM_CONSOLE {
            get {
                return ResourceManager.GetString("SETUP_FORM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        internal static string SETUP_FORM_CURRENT_POSITION {
            get {
                return ResourceManager.GetString("SETUP_FORM_CURRENT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        internal static string SETUP_FORM_DATE_FORMAT {
            get {
                return ResourceManager.GetString("SETUP_FORM_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string SETUP_FORM_DELETE {
            get {
                return ResourceManager.GetString("SETUP_FORM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string SETUP_FORM_DOMAIN {
            get {
                return ResourceManager.GetString("SETUP_FORM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SETUP_FORM_ENABLED {
            get {
                return ResourceManager.GetString("SETUP_FORM_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string SETUP_FORM_FILE {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfiles|*.log|All files|*.*.
        /// </summary>
        internal static string SETUP_FORM_FILE_FILTER {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string SETUP_FORM_FILTER {
            get {
                return ResourceManager.GetString("SETUP_FORM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string SETUP_FORM_FORMAT {
            get {
                return ResourceManager.GetString("SETUP_FORM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwards.
        /// </summary>
        internal static string SETUP_FORM_FORWARDS {
            get {
                return ResourceManager.GetString("SETUP_FORM_FORWARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy.
        /// </summary>
        internal static string SETUP_FORM_HTTP_PROXY {
            get {
                return ResourceManager.GetString("SETUP_FORM_HTTP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item count.
        /// </summary>
        internal static string SETUP_FORM_ITEM_COUNT {
            get {
                return ResourceManager.GetString("SETUP_FORM_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string SETUP_FORM_ITEM_COUNT_OF {
            get {
                return ResourceManager.GetString("SETUP_FORM_ITEM_COUNT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port.
        /// </summary>
        internal static string SETUP_FORM_LOCAL_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_LOCAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string SETUP_FORM_MOVE_DOWN {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        internal static string SETUP_FORM_MOVE_FIRST {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to bottom.
        /// </summary>
        internal static string SETUP_FORM_MOVE_LAST {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string SETUP_FORM_MOVE_UP {
            get {
                return ResourceManager.GetString("SETUP_FORM_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SETUP_FORM_NAME {
            get {
                return ResourceManager.GetString("SETUP_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SETUP_FORM_PASSWORD {
            get {
                return ResourceManager.GetString("SETUP_FORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string SETUP_FORM_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string SETUP_FORM_PROTOCOL {
            get {
                return ResourceManager.GetString("SETUP_FORM_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote port.
        /// </summary>
        internal static string SETUP_FORM_REMOTE_PORT {
            get {
                return ResourceManager.GetString("SETUP_FORM_REMOTE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string SETUP_FORM_SHARED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks.
        /// </summary>
        internal static string SETUP_FORM_SOCKS {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Socks server.
        /// </summary>
        internal static string SETUP_FORM_SOCKS_SERVER_ENABLED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS_SERVER_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Socks server.
        /// </summary>
        internal static string SETUP_FORM_SOCKS_SERVER_SHARED {
            get {
                return ResourceManager.GetString("SETUP_FORM_SOCKS_SERVER_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoutDuTunnel (Client) - Configuration.
        /// </summary>
        internal static string SETUP_FORM_TITLE {
            get {
                return ResourceManager.GetString("SETUP_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        internal static string SETUP_FORM_TUNNEL {
            get {
                return ResourceManager.GetString("SETUP_FORM_TUNNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SETUP_FORM_USER {
            get {
                return ResourceManager.GetString("SETUP_FORM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP binary stream.
        /// </summary>
        internal static string SETUPFORM_HTTP_BINARY_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_BINARY_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP SOAP stream.
        /// </summary>
        internal static string SETUPFORM_HTTP_SOAP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_HTTP_SOAP_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string SETUPFORM_INVALID_INPUT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number must be set between {0} and {1}.
        /// </summary>
        internal static string SETUPFORM_INVALID_PORT {
            get {
                return ResourceManager.GetString("SETUPFORM_INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local binary stream.
        /// </summary>
        internal static string SETUPFORM_IPC_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_IPC_REMOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP binary stream.
        /// </summary>
        internal static string SETUPFORM_TCP_REMOTING {
            get {
                return ResourceManager.GetString("SETUPFORM_TCP_REMOTING", resourceCulture);
            }
        }
    }
}
