//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.Server.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for {0}: inactive or nonexistent account.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for {0}: bad password.
        /// </summary>
        public static string ACCESS_DENIED_BAD_PASSWORD {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access granted to {0}.
        /// </summary>
        public static string ACCESS_GRANTED {
            get {
                return ResourceManager.GetString("ACCESS_GRANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required.
        /// </summary>
        public static string ADMIN_REQUIRED {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cid not found.
        /// </summary>
        public static string CID_NOT_FOUND {
            get {
                return ResourceManager.GetString("CID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0} ({1}).
        /// </summary>
        public static string CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0} from {1} session was killed by {2}.
        /// </summary>
        public static string CONNECTION_KILLED {
            get {
                return ResourceManager.GetString("CONNECTION_KILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection refused to {0}:{1} {2}.
        /// </summary>
        public static string CONNECTION_REFUSED {
            get {
                return ResourceManager.GetString("CONNECTION_REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout: {0}.
        /// </summary>
        public static string CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection idle timeout is not set for {0}, using default: {1} hour(s).
        /// </summary>
        public static string DEFAULT_CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("DEFAULT_CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session idle timeout is not set for {0}, using default: {1} hour(s).
        /// </summary>
        public static string DEFAULT_SESSION_TIMEOUT {
            get {
                return ResourceManager.GetString("DEFAULT_SESSION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from {0}.
        /// </summary>
        public static string DISCONNECTED {
            get {
                return ResourceManager.GetString("DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection detected.
        /// </summary>
        public static string DISCONNECTION_DETECTED {
            get {
                return ResourceManager.GetString("DISCONNECTION_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [server] .
        /// </summary>
        public static string SERVER_SIDE {
            get {
                return ResourceManager.GetString("SERVER_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server started, press enter key to exit....
        /// </summary>
        public static string SERVER_STARTED {
            get {
                return ResourceManager.GetString("SERVER_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -=[ BoutDuTunnel Server v{0} - Sebastien Lebreton ]=-.
        /// </summary>
        public static string SERVER_TITLE {
            get {
                return ResourceManager.GetString("SERVER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} session was killed by {1}.
        /// </summary>
        public static string SESSION_KILLED {
            get {
                return ResourceManager.GetString("SESSION_KILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session closed for {0}.
        /// </summary>
        public static string SESSION_LOGOUT {
            get {
                return ResourceManager.GetString("SESSION_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timeout: {0}.
        /// </summary>
        public static string SESSION_TIMEOUT {
            get {
                return ResourceManager.GetString("SESSION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sid not found.
        /// </summary>
        public static string SID_NOT_FOUND {
            get {
                return ResourceManager.GetString("SID_NOT_FOUND", resourceCulture);
            }
        }
    }
}
