//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check parameters!.
        /// </summary>
        internal static string CHECK_PARAMETERS {
            get {
                return ResourceManager.GetString("CHECK_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client started, press enter key to exit....
        /// </summary>
        internal static string CLIENT_STARTED {
            get {
                return ResourceManager.GetString("CLIENT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -=[ BoutDuTunnel Client v{0} - Sebastien LEBRETON ]=-.
        /// </summary>
        internal static string CLIENT_TITLE {
            get {
                return ResourceManager.GetString("CLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server (check proxy settings).
        /// </summary>
        internal static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session-id (Sid): {0}.
        /// </summary>
        internal static string CURRENT_SID {
            get {
                return ResourceManager.GetString("CURRENT_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} already in use, disabling forward to {1}:{2}.
        /// </summary>
        internal static string FORWARD_CANCELED {
            get {
                return ResourceManager.GetString("FORWARD_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding {0}:{1} to {2}:{3}.
        /// </summary>
        internal static string FORWARDING {
            get {
                return ResourceManager.GetString("FORWARDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display help.
        /// </summary>
        internal static string HELP_HELP {
            get {
                return ResourceManager.GetString("HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter domain: .
        /// </summary>
        internal static string INPUT_PROXY_DOMAIN {
            get {
                return ResourceManager.GetString("INPUT_PROXY_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password (hidden): .
        /// </summary>
        internal static string INPUT_PROXY_PASSWORD {
            get {
                return ResourceManager.GetString("INPUT_PROXY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username: .
        /// </summary>
        internal static string INPUT_PROXY_USERNAME {
            get {
                return ResourceManager.GetString("INPUT_PROXY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number must be set between {0} and {1}.
        /// </summary>
        internal static string INVALID_PORT {
            get {
                return ResourceManager.GetString("INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handshake with socks handler.
        /// </summary>
        internal static string INVALID_SOCKS_HANDSHAKE {
            get {
                return ResourceManager.GetString("INVALID_SOCKS_HANDSHAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill an existing connection, given his sid and cid.
        /// </summary>
        internal static string KILL_CONNECTION_HELP {
            get {
                return ResourceManager.GetString("KILL_CONNECTION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill an existing session, given his sid.
        /// </summary>
        internal static string KILL_SESSION_HELP {
            get {
                return ResourceManager.GetString("KILL_SESSION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all sessions and connections.
        /// </summary>
        internal static string MONITOR_HELP {
            get {
                return ResourceManager.GetString("MONITOR_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid socks handler found.
        /// </summary>
        internal static string NO_VALID_SOCKS_HANDLER {
            get {
                return ResourceManager.GetString("NO_VALID_SOCKS_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct connexion without proxy.
        /// </summary>
        internal static string NOT_USING_PROXY {
            get {
                return ResourceManager.GetString("NOT_USING_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication requested.
        /// </summary>
        internal static string PROXY_AUTH_REQUESTED {
            get {
                return ResourceManager.GetString("PROXY_AUTH_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks bind request unsupported.
        /// </summary>
        internal static string SOCKS_BIND_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS_BIND_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} already in use, disabling Socks server.
        /// </summary>
        internal static string SOCKS_SERVER_DISABLED {
            get {
                return ResourceManager.GetString("SOCKS_SERVER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks server listening to {0}:{1}.
        /// </summary>
        internal static string SOCKS_SERVER_STARTED {
            get {
                return ResourceManager.GetString("SOCKS_SERVER_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks4 request handled.
        /// </summary>
        internal static string SOCKS4_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS4_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks4A request handled.
        /// </summary>
        internal static string SOCKS4A_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS4A_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown address type in Socks5 request.
        /// </summary>
        internal static string SOCKS5_ADDRESS_TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("SOCKS5_ADDRESS_TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Socks5 version.
        /// </summary>
        internal static string SOCKS5_BAD_VERSION {
            get {
                return ResourceManager.GetString("SOCKS5_BAD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported IPV6 addresses in Socks5 request.
        /// </summary>
        internal static string SOCKS5_IPV6_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_IPV6_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed method enumeration in Socks5 request.
        /// </summary>
        internal static string SOCKS5_MALFORMED_METHOD_ENUM {
            get {
                return ResourceManager.GetString("SOCKS5_MALFORMED_METHOD_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Socks5 authentication supported.
        /// </summary>
        internal static string SOCKS5_NO_AUTHENTICATION_SUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_NO_AUTHENTICATION_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks5 request handled.
        /// </summary>
        internal static string SOCKS5_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS5_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP unsupported in Socks5 request.
        /// </summary>
        internal static string SOCKS5_UDP_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_UDP_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command in Socks5 request.
        /// </summary>
        internal static string SOCKS5_UNKNOWN_COMMAND {
            get {
                return ResourceManager.GetString("SOCKS5_UNKNOWN_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} already in use, disabling TCP server.
        /// </summary>
        internal static string TCP_SERVER_DISABLED {
            get {
                return ResourceManager.GetString("TCP_SERVER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using proxy: {0}.
        /// </summary>
        internal static string USING_PROXY {
            get {
                return ResourceManager.GetString("USING_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatch between client and server.
        /// </summary>
        internal static string VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("VERSION_MISMATCH", resourceCulture);
            }
        }
    }
}
