//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdt.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bdt.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client started, press enter key to exit....
        /// </summary>
        internal static string CLIENT_STARTED {
            get {
                return ResourceManager.GetString("CLIENT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -=[ BoutDuTunnel Client v{0} - Sebastien LEBRETON ]=-.
        /// </summary>
        internal static string CLIENT_TITLE {
            get {
                return ResourceManager.GetString("CLIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to server (check proxy settings).
        /// </summary>
        internal static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port {0} already in use, disabling forward to {1}:{2}.
        /// </summary>
        internal static string FORWARD_CANCELED {
            get {
                return ResourceManager.GetString("FORWARD_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forwarding {0}:{1} to {2}:{3}.
        /// </summary>
        internal static string FORWARDING {
            get {
                return ResourceManager.GetString("FORWARDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter domain: .
        /// </summary>
        internal static string INPUT_PROXY_DOMAIN {
            get {
                return ResourceManager.GetString("INPUT_PROXY_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter password (hidden): .
        /// </summary>
        internal static string INPUT_PROXY_PASSWORD {
            get {
                return ResourceManager.GetString("INPUT_PROXY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter username: .
        /// </summary>
        internal static string INPUT_PROXY_USERNAME {
            get {
                return ResourceManager.GetString("INPUT_PROXY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number must be set between {0} and {1}.
        /// </summary>
        internal static string INVALID_PORT {
            get {
                return ResourceManager.GetString("INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid handshake with socks handler.
        /// </summary>
        internal static string INVALID_SOCKS_HANDSHAKE {
            get {
                return ResourceManager.GetString("INVALID_SOCKS_HANDSHAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No valid socks handler found.
        /// </summary>
        internal static string NO_VALID_SOCKS_HANDLER {
            get {
                return ResourceManager.GetString("NO_VALID_SOCKS_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direct connexion without proxy.
        /// </summary>
        internal static string NOT_USING_PROXY {
            get {
                return ResourceManager.GetString("NOT_USING_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy authentication requested.
        /// </summary>
        internal static string PROXY_AUTH_REQUESTED {
            get {
                return ResourceManager.GetString("PROXY_AUTH_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks bind request unsupported.
        /// </summary>
        internal static string SOCKS_BIND_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS_BIND_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port {0} already in use, disabling Socks server.
        /// </summary>
        internal static string SOCKS_SERVER_DISABLED {
            get {
                return ResourceManager.GetString("SOCKS_SERVER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks server listening to {0}:{1}.
        /// </summary>
        internal static string SOCKS_SERVER_STARTED {
            get {
                return ResourceManager.GetString("SOCKS_SERVER_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks4 request handled.
        /// </summary>
        internal static string SOCKS4_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS4_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks4A request handled.
        /// </summary>
        internal static string SOCKS4A_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS4A_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown address type in Socks5 request.
        /// </summary>
        internal static string SOCKS5_ADDRESS_TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("SOCKS5_ADDRESS_TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad Socks5 version.
        /// </summary>
        internal static string SOCKS5_BAD_VERSION {
            get {
                return ResourceManager.GetString("SOCKS5_BAD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported IPV6 addresses in Socks5 request.
        /// </summary>
        internal static string SOCKS5_IPV6_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_IPV6_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Malformed method enumeration in Socks5 request.
        /// </summary>
        internal static string SOCKS5_MALFORMED_METHOD_ENUM {
            get {
                return ResourceManager.GetString("SOCKS5_MALFORMED_METHOD_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Socks5 authentication supported.
        /// </summary>
        internal static string SOCKS5_NO_AUTHENTICATION_SUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_NO_AUTHENTICATION_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Socks5 request handled.
        /// </summary>
        internal static string SOCKS5_REQUEST_HANDLED {
            get {
                return ResourceManager.GetString("SOCKS5_REQUEST_HANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UDP unsupported in Socks5 request.
        /// </summary>
        internal static string SOCKS5_UDP_UNSUPPORTED {
            get {
                return ResourceManager.GetString("SOCKS5_UDP_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown command in Socks5 request.
        /// </summary>
        internal static string SOCKS5_UNKNOWN_COMMAND {
            get {
                return ResourceManager.GetString("SOCKS5_UNKNOWN_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Using proxy: {0}.
        /// </summary>
        internal static string USING_PROXY {
            get {
                return ResourceManager.GetString("USING_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version mismatch between client and server.
        /// </summary>
        internal static string VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("VERSION_MISMATCH", resourceCulture);
            }
        }
    }
}
